import './vendor';

import './components/_loader'
import './components/_menu'
import './components/_simple-slider'
import './components/_animated-line'
import './components/_dropdown'
import './components/_faq'
import './components/_plan-slider'
import './components/_partners'
import './components/_cursor'
import './components/_gallery'
import './components/_gallery1'
import './components/_gallery2'
import './components/_scaled-block'
import './components/_animated-header'
